skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrowq32026 = "FtJVZ3vupN4vkUXsdBafqEhy3ACWCGKkQmmegL6krtdC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
